development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: Slackr_production
#change the production url to heroku thingy
#{ "redis://localhost:6379/1" }
# "redis://h:p70cf4dbb6e4e721f44e113ba24781bb5ec287131691ec63b98beb3b174861611@ec2-18-215-99-173.compute-1.amazonaws.com:40849"